CREATE TYPE public.app_role AS ENUM ('customer','staff','admin');
CREATE TABLE public.profiles (id uuid PRIMARY KEY, full_name text, email text, avatar_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_own_select ON public.profiles FOR SELECT TO authenticated USING (id=auth.uid());
CREATE POLICY profiles_own_update ON public.profiles FOR UPDATE TO authenticated USING (id=auth.uid()) WITH CHECK (id=auth.uid());
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL DEFAULT 'customer', UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY roles_own_read ON public.user_roles FOR SELECT TO authenticated USING (user_id=auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE FUNCTION public.create_customer_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.profiles(id,email,full_name) VALUES(new.id,new.email,new.raw_user_meta_data->>'full_name'); INSERT INTO public.user_roles(user_id,role) VALUES(new.id,'customer'); RETURN new; END $$;
CREATE TRIGGER on_customer_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_customer_profile();
CREATE TABLE public.menu_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, description text NOT NULL DEFAULT '', price numeric(8,2) NOT NULL, category text NOT NULL, cuisine text NOT NULL, image_url text, calories integer NOT NULL DEFAULT 0, protein numeric(6,1) NOT NULL DEFAULT 0, carbohydrates numeric(6,1) NOT NULL DEFAULT 0, fat numeric(6,1) NOT NULL DEFAULT 0, spice_level text NOT NULL DEFAULT 'Mild', is_vegetarian boolean NOT NULL DEFAULT true, is_vegan boolean NOT NULL DEFAULT false, is_available boolean NOT NULL DEFAULT true, preparation_time integer NOT NULL DEFAULT 20, average_rating numeric(3,1) NOT NULL DEFAULT 4.5, total_reviews integer NOT NULL DEFAULT 0, allergens text[] NOT NULL DEFAULT '{}', ingredients text[] NOT NULL DEFAULT '{}', dietary_tags text[] NOT NULL DEFAULT '{}', meal_types text[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.menu_items TO anon,authenticated; GRANT INSERT,UPDATE,DELETE ON public.menu_items TO authenticated; GRANT ALL ON public.menu_items TO service_role;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY menu_public_read ON public.menu_items FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY menu_admin_write ON public.menu_items FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY menu_staff_availability ON public.menu_items FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'staff')) WITH CHECK (public.has_role(auth.uid(),'staff'));
CREATE TABLE public.customer_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE, food_type text NOT NULL DEFAULT 'No Preference', cuisines text[] NOT NULL DEFAULT '{}', spice_level text NOT NULL DEFAULT 'Medium', dietary_requirements text[] NOT NULL DEFAULT '{}', allergies text[] NOT NULL DEFAULT '{}', budget_min numeric(8,2) NOT NULL DEFAULT 0, budget_max numeric(8,2) NOT NULL DEFAULT 1000, meal_type text NOT NULL DEFAULT 'Dinner', updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.customer_preferences TO authenticated; GRANT ALL ON public.customer_preferences TO service_role;
ALTER TABLE public.customer_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY preferences_own ON public.customer_preferences FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE TABLE public.favorites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, menu_item_id uuid NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,menu_item_id));
GRANT SELECT,INSERT,DELETE ON public.favorites TO authenticated; GRANT ALL ON public.favorites TO service_role;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
CREATE POLICY favorites_own ON public.favorites FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE TABLE public.recommendations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, preference_snapshot jsonb NOT NULL, algorithm_version text NOT NULL DEFAULT '1.0', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.recommendations TO authenticated; GRANT ALL ON public.recommendations TO service_role;
ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY recommendations_own ON public.recommendations FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE TABLE public.recommendation_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), recommendation_id uuid NOT NULL REFERENCES public.recommendations(id) ON DELETE CASCADE, menu_item_id uuid NOT NULL REFERENCES public.menu_items(id), score integer NOT NULL, ranking integer NOT NULL, explanation text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.recommendation_items TO authenticated; GRANT ALL ON public.recommendation_items TO service_role;
ALTER TABLE public.recommendation_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY recommendation_items_own ON public.recommendation_items FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.recommendations r WHERE r.id=recommendation_id AND r.user_id=auth.uid())) WITH CHECK (EXISTS(SELECT 1 FROM public.recommendations r WHERE r.id=recommendation_id AND r.user_id=auth.uid()));
CREATE TABLE public.feedback (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, menu_item_id uuid NOT NULL REFERENCES public.menu_items(id), recommendation_id uuid REFERENCES public.recommendations(id), rating integer NOT NULL CHECK(rating BETWEEN 1 AND 5), liked boolean, comment text, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.feedback TO authenticated; GRANT ALL ON public.feedback TO service_role;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY feedback_own ON public.feedback FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());